from markov_chain import MarkovChain
import unittest


class MarkovChainTest(unittest.TestCase):
    def test_init(self):
        '''Checks that the Markov Chain represents the corpus correctly.'''
        fish_list = [
            "one", "fish", "two", "fish", "red", "fish", "blue", "fish"
        ]
        mark = MarkovChain(fish_list)

        # test for the correct number of keys in the Markov Chain object
        states_of_fish_list = len(set(fish_list))
        states_of_mark = len(mark.chain.keys())
        assert states_of_mark == states_of_fish_list

        # test for the correct number of state transitions
        number_of_state_transitions = 0
        states = list(mark.chain.keys())
        for state in states:
            tokens_after_state = 0
            transitions_for_one_state = mark.chain[state]
            states_after = list(transitions_for_one_state.keys())
            for word_type in states_after:
                tokens_after_state += transitions_for_one_state[word_type]
            number_of_state_transitions += tokens_after_state
        assert number_of_state_transitions == 7

    def test_random_walk(self):
        '''The sentence generated follows the Markov Chain algorithm.'''
        fish_list = [
            "one", "fish", "two", "fish", "red", "fish", "blue", "fish"
        ]
        mark = MarkovChain(fish_list)
        # store a list of words generated by a random walk
        sentence = mark.random_walk().split()
        for i in range(len(sentence) - 1):
            word = sentence[i]
            word_after = sentence[i + 1]
            # make sure that word_after is allowed to come after the word
            states_that_come_next = list(mark.chain[word].keys())
            assert word_after in states_that_come_next


if __name__ == "__main__":
    unittest.main()
